<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.g575RUu' shared service.

return $this->privates['.service_locator.g575RUu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'carRepository' => ['privates', 'App\\Repository\\CarRepository', 'getCarRepositoryService.php', true],
    'settingRepository' => ['privates', 'App\\Repository\\Admin\\SettingRepository', 'getSettingRepositoryService.php', true],
], [
    'carRepository' => 'App\\Repository\\CarRepository',
    'settingRepository' => 'App\\Repository\\Admin\\SettingRepository',
]);
