<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.aTXG_3U' shared service.

return $this->privates['.service_locator.aTXG_3U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'car' => ['privates', '.errored..service_locator.aTXG_3U.App\\Entity\\Car', NULL, 'Cannot autowire service ".service_locator.aTXG_3U": it references class "App\\Entity\\Car" but no such service exists.'],
], [
    'car' => 'App\\Entity\\Car',
]);
