<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2h2l0ED' shared service.

return $this->privates['.service_locator.2h2l0ED'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'advertisementRepository' => ['privates', 'App\\Repository\\Admin\\AdvertisementRepository', 'getAdvertisementRepositoryService.php', true],
], [
    'advertisementRepository' => 'App\\Repository\\Admin\\AdvertisementRepository',
]);
