<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxGBtqj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxGBtqj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIxGBtqj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIxGBtqj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIxGBtqj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IxGBtqj',
    'container.build_id' => 'e796a925',
    'container.build_time' => 1578854434,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxGBtqj');
